---
title: "R"
output: github_document
---


```{r}
library(ggplot2)
library(dplyr)
library(GGally)
library(readr)
library(ggjoy)
library(FactoMineR)
library(factoextra)
library(ggpubr)
Medicalpremium <- read_csv("C:/Users/malis/3rdYear/New folder (3)/New folder/Medicalpremium.csv")

df = Medicalpremium

lapply(df, class)

unique(df$NumberOfMajorSurgeries)
```


```{r}
ggplot(df, mapping=aes(x=Age, 
                       y=as.factor(NumberOfMajorSurgeries),
                       fill=as.factor(NumberOfMajorSurgeries))) +
  geom_boxplot() +
  geom_jitter(alpha=0.2, size=0.5)
```

```{r}
ggplot(df, aes(x=df$Age, y=as.factor(df$Diabetes), fill=as.factor(df$Diabetes))) +
  geom_boxplot()
```


```{r}
ggplot() +
  geom_point(df, mapping=aes(x=df$Weight, y=df$Height, color=as.factor(df$BloodPressureProblems)))
```


```{r}
ggcorr(df[c("Age", "Weight", "Height", "PremiumPrice")])
```


```{r}
ggplot() +
  geom_joy(df, mapping=aes(x=Age, y=as.factor(df$NumberOfMajorSurgeries), 
                           fill=as.factor(df$NumberOfMajorSurgeries)))
```


```{r}
ggplot() +
  geom_joy(df, mapping=aes(x=Age, y=as.factor(NumberOfMajorSurgeries), 
                           fill=as.factor(NumberOfMajorSurgeries))) + 
  facet_grid(~Diabetes, 
             labeller=labeller(.rows=label_both, .cols=label_both))
```


```{r}
ggplot() +
  geom_joy(df, mapping=aes(x=Age, y=as.factor(NumberOfMajorSurgeries), 
                           fill=as.factor(NumberOfMajorSurgeries))) + 
  facet_grid(~BloodPressureProblems, 
             labeller=labeller(.rows=label_both, .cols=label_both))

```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
df= df %>%
  mutate(BMI = df$Weight/((df$Height/100)^2)) %>%
  mutate(BMI_cat = cut(BMI, breaks=c(-Inf, 18.5, 24.5, 29.9, 34.9, Inf), 
                       labels=c("underweight", "normal", "overweight", "obese", "Extreme")))
```


```{r}
df
```


```{r}
ggplot() +
  geom_joy(df, mapping=aes(x=Age, y=BMI_cat, 
                           fill=BMI_cat)) +
  facet_grid(~Diabetes, 
             labeller=labeller(.rows=label_both, .cols=label_both))
  

```


```{r}
BMI.count = df %>%
  group_by(BMI_cat) %>%
  tally() %>%
  arrange(desc(n))

```


```{r}
ggplot() +
  geom_bar(df, mapping=aes(x=BMI_cat, fill=BMI_cat))
```


```{r}
ggplot() +
  geom_bar(df, mapping=aes(x=BMI_cat, fill=as.factor(AnyChronicDiseases)), position="fill")
```


```{r}
temp = df %>% 
  group_by(BMI_cat) %>%
  summarise(mean_price=mean(PremiumPrice)) %>%
  arrange(desc(mean_price))
```


```{r}
ggplot() +
  geom_bar(temp, mapping=aes(x=BMI_cat, y=mean_price), stat="identity")
```


```{r}
fun = function(cat) {
  temp = df %>% 
    group_by(df[c(cat)]) %>%
    summarise(mean_price=mean(PremiumPrice)) %>%
    arrange(desc(mean_price))
  temp[[cat]] = as.factor(temp[[cat]])
  ggplot() +
    geom_bar(temp, mapping=aes_string(x=cat, y="mean_price", fill=cat), stat="identity")
  }
  
```


```{r}

fun("BloodPressureProblems")
```


```{r}
fun("AnyChronicDiseases")
```


```{r}
fun("NumberOfMajorSurgeries")
```


```{r}
temp = df %>%
  group_by(BMI_cat, AnyTransplants) %>%
  summarise(mean_price=mean(PremiumPrice))
temp

```


```{r}
ggplot() +
  geom_bar(temp, mapping=aes(x=BMI_cat, y=mean_price, fill=as.factor(AnyTransplants)),
                             position="dodge", stat="identity")
```


```{r}
ggplot() +
  geom_jitter(df, mapping=aes(x=Age, y=PremiumPrice, color=as.factor(NumberOfMajorSurgeries)))
```


```{r}
```


```{r}
```


## PCA



```{r}
library(FactoMineR)
library(factoextra)
```


```{r}

df.num = df[, c("Age", "Weight", "Height")]
```


```{r}
res.pca = PCA(df.num, scale.unit=T, ncp=2, graph=T)
```


```{r}
res.pca$eig
```


```{r}
get_eigenvalue(res.pca)

```


```{r}
fviz_eig(res.pca, addlabels=T, ylim=c(0, 50))
```


```{r}
var = get_pca_var(res.pca)
var$coord
var$cor
var$cos2
var$contrib
```
#### Correlation circle

```{r}
fviz_pca_var(res.pca, col.var="red")
```
#### Quality of representaion

```{r}
library(corrplot)
corrplot(var$cos2, is.corr=F)
```


```{r}
fviz_cos2(res.pca, choice="var", axes=1:2)

```


```{r}
fviz_pca_var(res.pca, col.var = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), 
             repel = TRUE # Avoid text overlapping
             )

```


```{r}
fviz_pca_var(res.pca, col.var="contrib", gradient.cols=c("#00AFBB", "#E7B800", "#FC4E07"))

```
### kmeans

```{r}
set.seed(123)
res.km = kmeans(var$coord, centers=2, nstart=25)
grp = as.factor(res.km$cluster)
grp

fviz_pca_var(res.pca, col.var=grp, palette=c("red", "tomato",
                                             "orange"),
             legend.title='cluster')
```


```{r}
res.desc = dimdesc(res.pca, axes=c(1, 2), proba=0.05)
res.desc
```
### Individuals

```{r}
ind = get_pca_ind(res.pca)

```


```{r}
fviz_pca_ind(res.pca, col.ind=as.factor(df$NumberOfMajorSurgeries),
             palette= c("red", "green", "blue", "purple"),
             geom.ind="point", 
             addEllipses=T)
```


```{r}
fviz_pca_biplot(res.pca, geom="point")
```

## Correspondence analysis
```{r}
dt = table(df$BMI_cat, as.factor(df$NumberOfMajorSurgeries))
dt
```


```{r}
library(gplots)
```


```{r}
balloonplot(dt, show.margins=F, label=F, main="surgeryn VS BMI_cat", ylab="", xlab="")

```


```{r}
chisq = chisq.test(dt)
chisq$statistic
corrplot(chisq$residuals, is.corr=F)
```


```{r}
res.ca = CA(dt)
```


```{r}
get_eigenvalue(res.ca)

```


```{r}
fviz_ca_row(res.ca, repel=T)
```


```{r}
res.ca$row$cos2
fviz_ca_row(res.ca, col.row="cos2", 
            gradient.cols=c("red", "green"))
```


```{r}
res.ca$col$cos2
```


```{r}
fviz_ca_biplot(res.ca, map="rowgreen", arrow=c(T, F), repel=T)
```
## Multiple correspondence analysis


```{r}
df.cat = df[, -c(which(colnames(df) %in% c("Age", "Weight", "Height", "BMI", "PremiumPrice")))]
```


```{r}
df.cat[, -c(which(colnames(df.cat) == "BMI_cat"))] = lapply(df.cat[, -c(which(colnames(df.cat) == "BMI_cat"))], factor)
```


```{r}
sapply(df.cat, class)
```


```{r}
summary(df.cat)
```


```{r}
res.mca = MCA(df.cat)
```


```{r}
fviz_screeplot(res.mca, addlabels=T, ylim=c(0, 45))
```


```{r}
fviz_mca_biplot(res.mca, repel=T, geom="point")
```


```{r}
fviz_mca_var(res.mca, choice="mca.cor", repel=T)
```


```{r}
res.mca$var$contrib
```


```{r}
fviz_mca_var(res.mca, col.var="cos2", gradient.cols=c("tomato", "yellow"), repel=T)
```


```{r}
fviz_mca_ind(res.mca, palette=c("yellow", "tomato"), repel=T, habillage="Diabetes", addEllipses=T, geom="point")
```
## Factor Analysis


```{r}
df[, -c(which(colnames(df) %in% c("Age", "Weight", "Height", "BMI", "PremiumPrice")))] = lapply(df.cat, factor)
```


```{r}
sapply(df, class)
X = df[, -c(which(colnames(df) == "PremiumPrice"))]
```


```{r}
dim(X)
```


```{r}
res.famd.a = FAMD(X)
```


```{r}
res.famd.a$eig
```


```{r}
fviz_screeplot(res.famd.a)
```
```{r}
fviz_mfa_ind(res.famd.a, habillage="BMI_cat", palette=c("red", "blue", "green", "yellow", "purple"), addEllipses=T, repel=T, geom="point")
```


```{r}
res.famd.a$var$contrib
```


```{r}
res.km.a = kmeans(res.famd.a$ind$coord, centers=4, nstart=25)
fviz_mfa_ind(res.famd.a, habillage=as.factor(res.km.a$cluster), palette=c("red", "blue", "green", "yellow", "purple", "black"), addEllipses=F, repel=T, geom="point")
```


```{r}
```


```{r}
X
```


```{r}
```


```{r}
```



```{r}
X.copy = X
```


```{r}
cat.cols = colnames(X)[lapply(X, class) == "factor"]
temp = lapply(X[, cat.cols], nlevels)
cat.cols.bi = colnames(X[, cat.cols])[temp == 2]
cat.cols.bi

for (col in cat.cols.bi) {
  X.copy[[col]] = recode_factor(X.copy[[col]], "0" = paste0(col, "0"),
                           "1" = paste0(col, "1"))
}

X.copy
```


```{r}
X.org = subset(X.copy, select = -c(BMI, BMI_cat))
```


```{r}
res.famd = FAMD(X.org)
```


```{r}

```


```{r}
```


```{r}
fviz_ellipses(res.famd, c("HistoryOfCancerInFamily", "Diabetes"), geom="point")
```


```{r}
fviz_famd_ind(res.famd, habillage="NumberOfMajorSurgeries", palette=c("red", "blue", "green", "yellow"), addEllipses=T, repel=T, geom="point")
```


```{r}
fviz_famd_ind(res.famd, habillage=X$BMI_cat, palette=c("red", "blue", "green", "yellow", "purple"), repel=T, geom="point")
```


```{r}
res.km = kmeans(res.famd$ind$coord, centers=3, nstart=25)
fviz_famd_ind(res.famd, habillage=as.factor(res.km$cluster), palette=c("tomato", "greenyellow", "skyblue"), repel=T, geom="point")
```
## hierachical clustering

```{r}
res.hcpc = HCPC(res.famd, graph=F)

```


```{r}
```


```{r}
fviz_cluster(res.hcpc,
             geom="point",
             repel = TRUE,            # Avoid label overlapping
             show.clust.cent = TRUE, # Show cluster centers
             palette = "jco",         # Color palette see ?ggpubr::ggpar
             ggtheme = theme_minimal(),
             main = "Factor map"
             )
```


```{r}
res.hcpc.a = HCPC(res.famd.a, graph=F, min=3)
```


```{r}
fviz_cluster(res.hcpc.a,
             geom="point",
             repel = TRUE,            # Avoid label overlapping
             show.clust.cent = TRUE, # Show cluster centers
             palette = "jco",         # Color palette see ?ggpubr::ggpar
             ggtheme = theme_minimal(),
             main = "Factor map"
             )
`
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```
