---
title: "R Notebook"
output: github_document
---

```{r, message=FALSE, warning=FALSE}
library(ggplot2)
library(RColorBrewer)
library(dplyr)
library(GGally)
library(readr)
library(ggjoy)
library(FactoMineR)
library(factoextra)
library(ggpubr)
library(corrplot)
library(cowplot)
library(glue)
library(car)
library(tidyverse)
library(gplots)
```


```{r, message=FALSE}
Medicalpremium <- read_csv("C:/Users/malis/3rdYear/New folder (3)/New folder/Medicalpremium.csv")
df = Medicalpremium
df
```

## preprocessing

```{r}
cat.cols = colnames(df[, -c(which(colnames(df) %in% c("Age", "Weight", "Height", "PremiumPrice")))])
num.cols = colnames(df[, c(which(colnames(df) %in% c("Age", "Weight", "Height", "PremiumPrice")))])
cat.cols
num.cols
```


```{r}
df[, cat.cols] = lapply(df[, cat.cols], factor)
lapply(df, class)
```


```{r}
dt = df
```

## feature engineering

```{r}
dt = dt %>%
  mutate(BMI = df$Weight/((df$Height/100)^2)) %>%
  mutate(BMI_cat = cut(BMI, breaks=c(-Inf, 18.5, 24.5, 29.9, 34.9, Inf), 
                       labels=c("underweight", "normal", "overweight", "obese", "Extreme")))
dt

dq = dt %>%
  mutate(Age_cat = cut(Age, breaks=c(17, 30, 59, Inf), labels=c("Young Adult", "Adult", "Old")))
dq
```


```{r}
cat.cols = colnames(dt)[lapply(dt, class) == "factor"]
num.cols = colnames(dt)[lapply(dt, class) == "numeric"]
```
## EDA

```{r}
attach(dt)
```


```{r}
ggplot(dt, mapping=aes(x=Age,
                       y=NumberOfMajorSurgeries, 
                       fill=NumberOfMajorSurgeries)) +
  geom_boxplot() +
  scale_fill_manual(values=c("darkred", "firebrick", "indianred2", "lightsalmon"))
  

```


```{r}
dt %>%
  group_by(NumberOfMajorSurgeries) %>%
  count()
```


```{r, purl=FALSE}
ggplot() +
  geom_joy(dt, mapping=aes(x=Age, 
                        y=NumberOfMajorSurgeries,
                        fill=BloodPressureProblems), scale=1, alpha=0.7, rel_min_height=0.02) +
  scale_fill_brewer(palette = "Set1")

```
```{r, purl=FALSE, fig.show="hide"}
cols = c("darkred", "firebrick", "indianred2", "salmon", "lightsalmon")
cat.cols = colnames(dq)[lapply(dt, class) == "factor"]
for (i in cat.cols) {
  plt = ggplot(dq, aes(y=!!sym(i), x=PremiumPrice, fill=!!sym(i))) +
    geom_boxplot() +
    scale_fill_manual(values=cols)
  print(plt)
}

```

```{r}
ggplot(dq, aes(y=AnyTransplants, x=PremiumPrice, fill=AnyTransplants)) +
    geom_boxplot() +
    scale_fill_manual(values=c("darkred", "indianred2")) +
  theme(legend.position = "bottom")
```


```{r}
ggplot(dq, aes(y=AnyChronicDiseases, x=PremiumPrice, fill=AnyChronicDiseases)) +
    geom_boxplot() +
    scale_fill_manual(values=c("darkred", "indianred2")) +
  theme(legend.position = "bottom")
```


```{r}
ggplot(dq, aes(y=HistoryOfCancerInFamily, x=PremiumPrice, fill=HistoryOfCancerInFamily)) +
    geom_boxplot() +
    scale_fill_manual(values=c("darkred", "indianred2")) +
  theme(legend.position = "bottom")
```


```{r}
```


```{r}
ggplot(dq, aes(y=BloodPressureProblems, x=PremiumPrice, fill=BloodPressureProblems)) +
    geom_boxplot() +
    scale_fill_manual(values=c("darkred", "indianred2"))
```


```{r}
ggplot(dq, aes(y=Diabetes, x=PremiumPrice, fill=Diabetes)) +
    geom_boxplot() +
    scale_fill_manual(values=c("darkred", "indianred2")) +
  theme(legend.position = "bottom")
```


```{r}
ggplot(dq, aes(y=NumberOfMajorSurgeries, x=PremiumPrice, fill=NumberOfMajorSurgeries)) +
    geom_boxplot() +
    scale_fill_manual(values=cols) +
  theme(legend.position = "bottom")
```


```{r}

plt1 = ggplot(dq, aes(y=NumberOfMajorSurgeries, x=PremiumPrice, fill=NumberOfMajorSurgeries)) +
    geom_boxplot() +
    scale_fill_manual(values=cols) +
  labs(y="") +
  theme(legend.position = "none")

temp = dq %>% 
  group_by(NumberOfMajorSurgeries) %>%
  summarise(mean_price=mean(PremiumPrice)) %>%
  arrange(desc(mean_price))
  
plt2 = ggplot(temp, aes(y=NumberOfMajorSurgeries, x=mean_price, fill=NumberOfMajorSurgeries)) +
    geom_bar(stat="identity") +
    scale_fill_manual(values = cols) +
    labs(x="mean Premium Price") +
  theme(legend.position = "none")



leg = get_legend(plt2 +
                   theme(legend.position = "bottom"))

cow1 = plot_grid(plt2, plt1, ncol=2, rel_heights=c(2, 1))

plot_grid(cow1 , leg, ncol=1, rel_heights = c(1, 0.1))
```




```{r, purl=FALSE}
cat.cols = colnames(dq)[lapply(dq, class) == "factor"]
for (i in cat.cols) {
  temp = dq %>% 
  group_by(!!sym(i)) %>%
  summarise(mean_price=mean(PremiumPrice)) %>%
  arrange(desc(mean_price))
  
  plt = ggplot(temp, aes(x=!!sym(i), y=mean_price, fill=!!sym(i))) +
    geom_bar(stat="identity") +
    scale_fill_manual(values = cols) +
    labs(y="mean Premium Price")
  print(plt)
}
```
```{r}
temp = dq %>% 
  group_by(Age_cat) %>%
  summarise(mean_price=mean(PremiumPrice)) %>%
  arrange(desc(mean_price))
  
  plt = ggplot(temp, aes(x=Age_cat, y=mean_price, fill=Age_cat)) +
    geom_bar(stat="identity") +
    scale_fill_manual(values = c("darkred", "indianred2", "lightsalmon")) +
    labs(y="mean Premium Price") +
    theme(legend.position = "bottom")
  print(plt)

```




```{r}
temp = dq %>% 
  group_by(Age) %>%
  summarise(mean_price=mean(PremiumPrice)) %>%
  arrange(desc(Age))
temp

ggplot(temp, mapping=aes(x=Age, y=mean_price)) +
  geom_point(color="indianred2") +
  geom_smooth(method = "lm", se=F, color="darkred") +
  labs(y="mean Premium Price")
```


```{r}
plt1 = ggplot(dt, mapping=aes(x=PremiumPrice, fill=KnownAllergies)) +
  geom_histogram(binwidth=2000, color="black") +
  scale_fill_manual(values=c("indianred2", "darkred")) +
  theme(legend.position = "none") +
  facet_wrap(~factor(KnownAllergies, levels=c(1, 0)), nrow=2) +
  labs(y="")
plt2 = ggplot(dt, mapping=aes(x=PremiumPrice, y=KnownAllergies, fill=KnownAllergies)) +
  geom_joy2(scale=0.8) +
  scale_fill_manual(values = c("indianred2", "darkred")) +
  theme(legend.position="none")
leg = get_legend(plt2 +
                   theme(legend.position = "bottom"))

cow1 = plot_grid(plt2, plt1, ncol=2, rel_heights=c(2, 1))

plot_grid(cow1 , leg, ncol=1, rel_heights = c(1, 0.1))
```


```{r, purl=FALSE}
plt1 = ggplot(dt, mapping=aes(x=PremiumPrice, fill=BloodPressureProblems)) +
  geom_histogram(binwidth=2500, color="black") +
  scale_fill_manual(values=c("indianred2", "darkred")) +
  theme(legend.position = "none") +
  facet_wrap(~factor(BloodPressureProblems, levels=c(1, 0)), nrow=2) +
  labs(y="")
plt2 = ggplot(dt, mapping=aes(x=PremiumPrice, y=BloodPressureProblems, fill=BloodPressureProblems)) +
  geom_joy2(scale=0.8) +
  scale_fill_manual(values = c("indianred2", "darkred")) +
  theme(legend.position="none")
leg = get_legend(plt2 +
                   theme(legend.position = "bottom"))

cow1 = plot_grid(plt2, plt1, ncol=2, rel_heights=c(2, 1))

plot_grid(cow1 , leg, ncol=1, rel_heights = c(1, 0.1))
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```



```{r}
histBox = function(var, ...) {
  plt1 = ggplot(dt, aes(x=!!sym(var))) +
    geom_histogram(..., color="black", fill="darkred") +
    xlab("")
  
  plt2 = ggplot(dt, aes(x=!!sym(var))) +
    geom_boxplot(fill="indianred2", color="black")
  
  plt3 = title = ggdraw()+
    draw_label(glue("Histogram and Boxplot of {var}"))
  
  cow1 = plot_grid(plt1, plt2, ncol=1, rel_heights=c(2, 1), align='v', axis='lr')
  plot_grid(plt3, cow1, ncol=1, rel_heights = c(0.1, 1))
  
  }


```


```{r, purl=FALSE}
histBox("Age", binwidth=1)

```


```{r}
histBox("PremiumPrice", binwidth=2500)
```

```{r}

```





```{r, purl=FALSE}
cat.cols = colnames(dq)[lapply(dq, class) == "factor"]
for (i in cat.cols) {
  plt = ggplot(dq, aes(x=!!sym(i), fill=!!sym(i))) +
    geom_bar() +
    scale_fill_brewer(palette="Set2")
  print(plt)
}
```



```{r}

```


```{r}
```


```{r}
```


```{r, purl=FALSE}
for (i in num.cols) {
  plt = ggplot(dt, aes(y=!!sym(i))) +
    geom_boxplot(fill="coral", color="black") +
    scale_fill_brewer(palette="Set2")
  print(plt)
}
```


```{r, message=FALSE, purl=FALSE}
ggpairs(dt[, num.cols])
```


```{r}
temp = num.cols[4]
num.cols[4] = num.cols[5]
num.cols[5] = temp
ggcorr(dt[, num.cols], label=T, label_round=3, low="white", mid="lightsalmon", high="darkred") +
  labs(title="Correlation Heatmap")


```


```{r}
model = lm(PremiumPrice ~ ., data=df)         

as.data.frame(vif(model))

```


```{r}

ggplot() +
  geom_bar(dq, mapping=aes(x=BMI_cat, fill=BloodPressureProblems), position="fill")

```


```{r}
ggplot() +
  geom_bar(dq, mapping=aes(x=BMI_cat, fill=BloodPressureProblems), position="fill")


```


```{r}
ggplot() +
  geom_bar(dq, mapping=aes(x=BMI_cat, fill=HistoryOfCancerInFamily), position="fill")
```


```{r}
tble = table(dt$KnownAllergies, dt$HistoryOfCancerInFamily)
chisq.test(dt$AnyChronicDiseases, dt$HistoryOfCancerInFamily)
temp = chisq.test(dt$Diabetes, dt$BloodPressureProblems)
temp$p.value
chisq.test(dt$AnyChronicDiseases, dt$AnyChronicDiseases)
balloonplot(tble, main ="housetasks", show.margins = FALSE)

```


```{r}
cat.cols = colnames(dt)[lapply(dt, class) == "factor"]
cat.cols = cat.cols[1:(length(cat.cols) - 1)]
mat = matrix(NA, nrow=length(cat.cols), ncol=length(cat.cols))
which(cat.cols == cat.cols[1])
for (i in cat.cols) {
  for (j in cat.cols) {
    I = which(cat.cols == i)
    J = which(cat.cols == j)
    if (i == j) {
      mat[I, J] == 0
    } else {
      tb = table(dt[[i]], dt[[j]])
      print(tb)
      mat[I, J] = chisq.test(tb)$p.value
    }
  }
}
mat
chi = as.data.frame(mat)
names(chi) = cat.cols
rownames(chi) = cat.cols
which(cat.cols == "HistoryOfCancerInFamily")
which(cat.cols == "KnownAllergies")
chi[6, 5] = 0
chi[5, 6] = 0
chi
ggcorr(chi, label = T, label_round = 3, hjust=0.7, size=3, cor_matrix = chi)
```


```{r}

```


```{r}
ggplot() +
  geom_bar(dq, mapping=aes(x=dt$BloodPressureProblems, fill=dt$Diabetes), position="fill")
```


```{r}
temp = dq %>% 
  group_by(AnyChronicDiseases) %>%
  summarise(mean_age=mean(Age)) %>%
  arrange(desc(mean_age))
  
ggplot(temp, aes(x=AnyChronicDiseases, y=mean_age, fill=AnyChronicDiseases)) +
    geom_bar(stat="identity") +
    scale_fill_manual(values = cols) +
    labs(y="mean Premium Age")
  
  
```


```{r}
ggplot(dq, aes(x=AnyChronicDiseases, fill=Age_cat)) +
  geom_bar(position = "fill")
```


```{r}
temp = num.cols[5]
q1 = quantile(df[[temp]], 0.25)
q3 = quantile(df[[temp]], 0.75)
IQR = q3 - q1
lb = q1 - 1.5*IQR
ub = q3 + 1.5*IQR
lb
ub
df[df[[temp]] < lb | df[[temp]] > ub, ]
```
```{r}
dtemp = dt
dtemp$ID = row.names(dtemp)
dtemp
temp = num.cols[-4]
temp
identify_outliers_in_all_variables <- function(data, k = 1.5) {
  outliers <- data.frame()

  for (column in names(data)) {
    if (column %in% temp) {
      # Calculate IQR for each variable
      Q1 <- quantile(data[[column]], 0.25)
      Q3 <- quantile(data[[column]], 0.75)
      IQR <- Q3 - Q1

      # Define upper and lower bounds
      lower_bound <- Q1 - k * IQR
      upper_bound <- Q3 + k * IQR

      # Identify outliers for the current variable
      variable_outliers <- data[(data[[column]] < lower_bound) | (data[[column]] > upper_bound), ]

      # Add to the overall outliers dataframe
      outliers <- rbind(outliers, variable_outliers)
    }
  }

  # Keep only rows where all numeric variables are outliers
  outliers <- outliers[duplicated(outliers), ]

  return(outliers)
}

identify_outliers_in_all_variables(dtemp)


```


```{r}
```

## FAMD

## FAMD with original data
```{r}
X = df[, -dim(df)[2]]
y = df[, dim(df)[2]]
```


```{r}
X.copy = X
cat.cols = colnames(X)[lapply(X, class) == "factor"]
cat.cols = cat.cols[1:(length(cat.cols) -1)]
for (col in cat.cols) {
  X[[col]] = recode_factor(X[[col]], "0" = paste0(col, "0"),
                           "1" = paste0(col, "1"))
}
```

```{r}

```


```{r}
X
res.famd = FAMD(X)
```


```{r}
res.famd$var$contrib
```


```{r}
fviz_famd_var(res.famd, "quanti.var", repel=T, col.var="contrib", gradient.cols=rev(cols))
```


```{r}
fviz_famd_var(res.famd, "quali.var", repel=T, col.var="contrib", gradient.cols=rev(cols))
```

```{r}
fviz_famd_var(res.famd, "var", repel=T, col.var="coord", gradient.cols=rev(cols))
```


```{r}
fviz_screeplot(res.famd)

```


```{r}
```


```{r}
```




```{r}
as.data.frame(res.famd$eig)

```
```{r}
res.famd$var$contrib[, 1:2]

```


```{r, purl=FALSE}
fviz_mfa_ind(res.famd, geom="point", habillage = "BloodPressureProblems")
```


```{r, purl=FALSE}
fviz_mfa_ind(res.famd, habillage="Diabetes", palette="Accent", addEllipses=F, repel=T, geom="point")

```




```{r}
res.km = kmeans(res.famd$ind$coord, centers=3, nstart=25, iter.max=50)
fviz_mfa_ind(res.famd, habillage=as.factor(res.km$cluster), palette=c("darkred", "indianred2", "salmon"), addEllipses=T, repel=T, geom="point")

```



```{r}
dt["cluster"] = as.factor(res.km$cluster)
dq["cluster"] = as.factor(res.km$cluster)

fviz_nbclust(X.copy, kmeans, method = "silhouette")
```
```{r}
write.csv(dt, "C:/Users/malis/code/ML/ML_project/data.csv", row.names=F)
```


```{r}
ggplot(dt, aes(x=cluster, y=PremiumPrice, color=cluster)) +
  geom_jitter() +
  labs(title="Visualizing clusters against Premium price")

ggplot(dt, aes(x=cluster, y=Age, color=cluster)) +
  geom_jitter() +
  labs(title="Visualizing clusters against Premium price")
 
  

```


```{r, purl=F}
ggplot(dt, aes(x=Age, y=PremiumPrice, color=as.factor(cluster))) +
  geom_point()
```
```{r}
X.exp = X
X.exp$cluster = dt$cluster
X.exp = X.exp[, -which(colnames(X.exp) %in% c("Height", "Weight", "Age"))]
temp = as.data.frame(table(X.exp$cluster, X.exp$Diabetes))
temp
temp = spread(temp, key=Var2, value=Freq)
temp[, -1] = round(temp[, -1] / rowSums(temp[, -1]), 2)
temp
for (i in colnames(X.exp)[-8]) {
  temp = as.data.frame(table(X.exp$cluster, X.exp[[i]]))
  temp =spread(temp, key=Var2, value=Freq)
  temp[, -1] = round(temp[, -1] / rowSums(temp[, -1]), 2)
  print(temp)
  if (which(colnames(X.exp) == i) == 1) {
    emp = temp
  } else {
    emp = merge(emp, temp, by="Var1")
  }
}
print(emp)

```


```{r}
ggplot() +
  geom_bar(dq, mapping=aes(x=cluster, fill=Age_cat), position="fill")

ggplot() +
  geom_bar(dt, mapping=aes(x=cluster, fill=Diabetes), position="fill")

cat.cols = colnames(dt)[lapply(dt, class) == "factor"]
cat.cols = cat.cols[1:(length(cat.cols) - 1)]

for (i in cat.cols) {
  plt = ggplot(dt, aes(x=cluster, fill=!!sym(i))) +
    geom_bar(position="fill") +
    scale_fill_brewer(palette="Set2")
  print(plt)
}

```


```{r, purl=FALSE}
temp = dt %>%
  group_by(cluster, NumberOfMajorSurgeries) %>%
  count()
temp

ggplot() +
  geom_bar(temp, mapping=aes(x=cluster, y=n, fill=NumberOfMajorSurgeries),
                             position="dodge", stat="identity")



```



```{r}
temp = dt[, c(cat.cols, "cluster")]
summary(temp[temp$cluster == 1, ])
summary(temp[temp$cluster == 2, ])
summary(temp[temp$cluster == 3, ])

```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}

```


```{r}
```


```{r}
```
## hierachical clustering with original data

```{r, purl=FALSE}
res.hcpc = HCPC(res.famd, graph=F, nb.clust=2)
```


```{r, purl=FALSE}
fviz_cluster(res.hcpc, geom="point")
```


```{r, purl=FALSE}
clust = res.hcpc$data.clust
dt["cluster"] = clust$clust
dt
ggplot(dt, aes(x=cluster, y=PremiumPrice)) +
  geom_jitter()
```


```{r, purl=FALSE}
X.a = dt[, -dim(df)[2]]
y.a = df[, dim(df)[2]]
X.a = X.a[, -dim(X.a)[2]]
```
## FAMD with BMI, BMI_cat

```{r, purl=FALSE}
res.famd.a = FAMD(X.a)
```


```{r, purl=FALSE}
fviz_mfa_ind(res.famd.a, habillage="BMI_cat", palette=c("red", "blue", "green", "yellow", "purple"), addEllipses=T, repel=T, geom="point")
```
```{r}
res.km.a = kmeans(res.famd.a$ind$coord, centers=4, nstart=25, iter.max=30)
fviz_mfa_ind(res.famd.a, habillage=as.factor(res.km.a$cluster), palette=c("red", "blue", "green", "yellow", "purple", "black"), addEllipses=F, repel=T, geom="point")
```


```{r, purl=FALSE}
dt["cluster"] = res.km.a$cluster
ggplot(dt, aes(x=cluster, y=PremiumPrice)) +
  geom_jitter()
```


```{r, purl=FALSE}
ggplot(dt, aes(x=cluster, y=Age)) +
  geom_jitter()
```


```{r, purl=FALSE}
ggplot(dt, aes(x=cluster, y=BMI)) +
  geom_jitter()
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

